### ISSUE TITLE
Error When Run as commit-msg Hook

### ISSUE THREAD

**Issue by Kurt-von-Laven** [pre-commit/mirrors-prettier#11]
# Repro Steps

1. Add Prettier to `.pre-commit-config.yaml` as shown below.
2. Run `pre-commit install --hook-type commit-msg --hook-type pre-commit` (e.g., because other commit-msg hooks are in use).
3. Make a commit.

```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
```

# Expected Results

Prettier succeeds or is skipped when run as a commit-msg hook like nearly all other hooks.

# Actual Results

Prettier outputs an error when run as a commit-msg hook.

```
prettier......................................................................Failed
- hook id: prettier
- exit code: 2

[error] No matching files. Patterns: .git/COMMIT_EDITMSG
```
