### ISSUE TITLE
Unexpected output when prettier as a pre-commit.com hook (files changes but not reported)

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/mirrors-prettier#17]
Based on a report I got from @cidrblock three days ago on https://github.com/ansible/ansible-navigator/pull/1013, it seems that when running prettier inside pre-commit one is likely to observe some weird behaviors related to its output in case something is happening, most likely is seeing less files being reported as modified than it does in reality.

On GHA a little bit different behavior can be seen where the modified files are not displayed one per line and instead they are joined as a single blob of text without any separator.

After some investigation I was able to narrow down and report the bug upstream at https://github.com/prettier/prettier/issues/12364 but there is more to it and sadly many of the issues observed seem to affect usage from within pre-commit more than other usages.

As I was able to come up with a workaround, I decided to log it here so other pre-commit users might be able to apply, especially as I have no knowledge on how fast pre-commit project would be able to deal with them (at least 3 different bugs involved and the project does not seem very active).

```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        # Original hook implementation is flaky due to *several* bugs described
        # in https://github.com/prettier/prettier/issues/12364
        # a) CI=1 needed to avoid incomplete output
        # b) two executions are needed because --list-different works correctly
        # only when run with --check as with --write the output will also
        # include other entries and logging level cannot be used to keep only
        # modified files listed (any file is listed using the log level, regardless if
        # is modified or not).
        # c) We avoid letting pre-commit pass each filename in order to avoid
        # running multiple instances in parallel. This also ensures that running
        # prettier from the command line behaves identically with the pre-commit
        # one. No real performance downsides.
        entry: env CI=1 bash -c "prettier --list-different . || true && prettier --loglevel=error --write ."
        pass_filenames: false
        args: []
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
```

I hope this could save someone's time. We might even consider applying these to the default hook definition if prettier itself fails to fix them?
