### ISSUE TITLE
Pre-commit hook with java plugin does not format java files

### ISSUE THREAD

**Issue by dmarshall-bing** [pre-commit/mirrors-prettier#24]
Hi, I am trying to use this pre-commit hook with the java-plugin (https://github.com/jhipster/prettier-java) for prettier. Here is the hook in my .pre-commit-config.yaml:
```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: [python]
        additional_dependencies:
          - prettier
          - jhipster/prettier-java
```
When I try to run the hook:
```
(dev) C:\Users\Daniel\Documents\ASCENT\ascent>pre-commit run prettier --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:jhipster/prettier-java,prettier.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
prettier.................................................................Passed
```
None of my java files are changed. Am I doing something wrong?

Thanks!

**Comment by asottile** [comment]
show all of your configuration(s) otherwise I can only guess and cannot help you

**Comment by dmarshall-bing** [comment]
Thanks for your response! Here is my whole yaml file:
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # checking for syntax
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # simple formatting
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      # checks for unresolved merge conflicts
      - id: check-merge-conflict
  # sort python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # format python code
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  # lint python code
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        # check for dead code
        additional_dependencies: [flake8-eradicate, flake8-bugbear]
  # format markdown, yaml, json, and others
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: [python]
        additional_dependencies:
          - prettier
          - jhipster/prettier-java
```
Let me know if you need any more info!

**Comment by dmarshall-bing** [comment]
This is the project, the java files reside in src/model
https://github.com/wmglab-duke/ascent

**Comment by asottile** [comment]
I don't see an npm package called `jhipster/prettier-java`

**Comment by dmarshall-bing** [comment]
solution was this:
```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: [python]
        additional_dependencies:
          - prettier
          - prettier-plugin-java
```
I misunderstood the syntax. Thanks!
