### ISSUE TITLE
Trying to add `prettier-plugin-tailwindcss` to `additional_dependencies` results in `Executable prettier not found`

### ISSUE THREAD

**Issue by paw-lu** [pre-commit/mirrors-prettier#30]
Trying to add [tailwindlabs/prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) as a plugin for prettier.

```yml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier-plugin-tailwindcss"
```

But when I try to run it I get

```console
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

Executable `prettier` not found
```

Prettier works as expected when the `additional_dependencies` section is removed.

---

Thanks a lot for this mirror!
