### ISSUE TITLE
Does prettier read the .prettierrc config file inside a git repo when ran via pre-commit?

### ISSUE THREAD

**Issue by gilesw** [pre-commit/mirrors-prettier#42]
I thought my .prettierrc was being read but it doesn't seem to be changing anything. I've seen other people changing the config per language like this by feeding the args in : 

```
# format java. Seperate from the above for different tab width
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        name: prettier-java
        types: [java]
        additional_dependencies:
          - prettier
          - prettier-plugin-java
        args: ["--tab-width", "4", "--print-width", "100"]
```
