### ISSUE TITLE
Prettier hook running was ignored after add it to yaml config?

### ISSUE THREAD

**Issue by hylerrix** [pre-commit/mirrors-prettier#45]
## Background

Hi, I'm studying [Next.js Enterprise Boilerplate](https://github.com/Blazity/next-enterprise), and it uses pre-commit.

When I wanted to customize it deeply, I got the 1st issue but got the solution in #11 by adding `stages: [commit]` to `.pre-commit-config.yaml`. And then added more lines to it:

```
- repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        stages: [commit]
        additional_dependencies:
          - prettier-plugin-tailwindcss
        args: ["--tab-width", "2", "--print-width", "120"]
```

## But when running `git commit` again, this process is ignored; how it comes?

![CleanShot 2023-07-19 at 15 32 22](https://github.com/pre-commit/mirrors-prettier/assets/19285461/b43605c1-9508-4429-be21-b6a8880100e9)

Thanks for your time!
