### ISSUE TITLE
additionalDependencies not loaded correctly

### ISSUE THREAD

**Issue by mashehu** [pre-commit/mirrors-prettier#46]
Since 3.0.0, I get the error:
`Cannot find package 'prettier-plugin-astro' imported from $PATH_TO_MY_REPO/noop.js`

My `pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.0
          - prettier-plugin-astro@^0.11.0
        args: [ --plugin=prettier-plugin-astro]
        files: \.(astro)$
```

Works fine if I use `v.2.7.1`.
