### ISSUE TITLE
[error] No matching files. Patterns: .git/COMMIT_EDITMSG

### ISSUE THREAD

**Issue by engineervix** [pre-commit/mirrors-prettier#5]
I'm encountering the above error in my pre-commit setup in a Django project. My `.pre-commit-config.yaml` is as follows:

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-docstring-first
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: (.*)/migrations
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude: >
          (?x)^(
              (.*)/static/vendors|
              (.*)/static/ico|
              ^.+\.html$|
              package-lock.json|
              yarn.lock|
              ^.+\.min\.(js|css)$
          )$
        additional_dependencies:
          - prettier@2.2.1
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.12.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          [
            "stylelint@13.7.2",
            "stylelint-config-sass-guidelines@7.1.0",
            "stylelint-config-prettier@8.0.2",
          ]
        exclude: >
          (?x)^(
              (.*)/static/vendors|
              (.*)/static/css/main\.css|
              ^.+\.min\.(css)$
          )$
```
Here is a terminal recording demonstrating the problem:

https://user-images.githubusercontent.com/7713776/103385550-9ca55c80-4b03-11eb-9833-4b670911a9d1.mp4

Thanks
