### ISSUE TITLE
Getting an unknown "command" error

### ISSUE THREAD

**Issue by DeltaXWizard** [pre-commit/mirrors-prettier#7]
Hey, I'm not sure if this repo's still maintained, but I've been getting this specific error on my git commit hook and I'm not sure why (I had no luck trying to resolve this on my own):

![image](https://user-images.githubusercontent.com/33706469/112762591-67a78980-8fce-11eb-8939-81057aec4b0e.png)

Here's the `.pre-commit-config.yaml`:
```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
 ```
 
 It seems to work for some objects (in a test/dummy sense) but I always get that particular repetition of lines.
